### ISSUE TITLE
Repetition

### ISSUE THREAD

**Issue by victoryosiobe** [abtzpro/NewKid-LLM#1]
![Screenshot_20230722_080609](https://github.com/abtzpro/NewKid-LLM/assets/119448316/b5ef9d01-d4f1-49e6-ae5b-fc23a4451606)

**Comment by abtzpro** [comment]
Thank you kindly for the issue submission. It has been fixed. I incorporated this change while in the Emergency room yesterday. I must have missed the duplication error during the rush.
